=== jbenner-radham/json-schema-lab/schemas/vcard.json
{
    "$id": "https://example.com/schemas/vcard.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "vCard",
    "description": "A format for representing and exchanging a variety of information about individuals and other entities.",
    "type": "object",
    "definitions": {
        "telephones": {
            "enum": [
                "cell",
                "fax",
                "pager",
                "text",
                "textphone",
                "video",
                "voice"
            ]
        },
        "types": {
            "enum": [
                "home",
                "work"
            ]
        }
    },
    "properties": {
        "kind": {
            "enum": [
                "group",
                "individual",
                "location",
                "org"
            ],
            "type": "string"
        },
        "fn": {
            "type": "string",
            "title": "Formatted Name"
        },
        "familyName": {
            "type": "string"
        },
        "givenName": {
            "type": "string"
        },
        "additionalName": {
            "type": "string"
        },
        "honorificPrefix": {
            "type": "string"
        },
        "honorificSuffix": {
            "type": "string"
        },
        "nickname": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "role": {
            "type": "string"
        },
        "email": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "home",
                        "work"
                    ],
                    "type": "string"
                },
                "value": {
                    "type": "string",
                    "format": "email"
                }
            }
        },
        "url": {
            "type": "string",
            "format": "uri"
        },
        "telephone": {
            "type": "object",
            "properties": {
                "type": {
                    "type": [
                        "string",
                        "array"
                    ],
                    "if": {
                        "type": "string"
                    },
                    "then": {
                        "type": "string",
                        "oneOf": [
                            {
                                "$ref": "#/definitions/types"
                            },
                            {
                                "$ref": "#/definitions/telephones"
                            }
                        ]
                    },
                    "else": {
                        "type": "array",
                        "uniqueItems": true,
                        "anyOf": [
                            {
                                "items": [
                                    {
                                        "$ref": "#/definitions/types"
                                    },
                                    {
                                        "$ref": "#/definitions/telephones"
                                    }
                                ]
                            }
                        ]
                    },
                    "default": "voice"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "required": [
        "fn",
        "kind"
    ]
}

=== jbenner-radham/json-schema-lab/data/jane-doe.json
{
    "kind": "individual",
    "fn": "Jane Doe",
    "title": "Example",
    "role": "faux person",
    "email": {
        "type": "work",
        "value": "jane.doe+work@example.com"
    },
    "telephone": {
        "type": [
            "work",
            "voice"
        ],
        "value": "555.867.5309"
    },
    "url": "https://jane-doe.example.com/"
}
